import * as React from 'react';

import Layout from '@/components/layout/Layout';
import Seo from '@/components/Seo';

export default function HomePage() {
  return (
    <Layout title={<>Yuantian's Blog</>}>
      <Seo/>
      <div className="textbox center-box">
        <h1>Heading 1</h1>
          <p>Lorem ipsum odor amet, consectetuer adipiscing elit. Mi volutpat mus velit platea nam. Sapien erat pretium magna feugiat finibus urna. Ac montes molestie per porttitor suspendisse aliquet primis. Laoreet pulvinar hac sit tincidunt commodo tempus quis tempus. Curabitur ante ex enim; cursus non dictumst lobortis. Praesent primis mattis non imperdiet dapibus. Curabitur faucibus rutrum primis mi etiam eros mauris habitasse.</p>
        <h2>Heading 2</h2>
          <p>Lorem ipsum odor amet, consectetuer adipiscing elit. Mi volutpat mus velit platea nam. Sapien erat pretium magna feugiat finibus urna. Ac montes molestie per porttitor suspendisse aliquet primis. Laoreet pulvinar hac sit tincidunt commodo tempus quis tempus. Curabitur ante ex enim; cursus non dictumst lobortis. Praesent primis mattis non imperdiet dapibus. Curabitur faucibus rutrum primis mi etiam eros mauris habitasse.</p>
          <p>Malesuada sagittis ornare tincidunt mauris fames scelerisque metus magna. Molestie placerat pharetra nunc ultrices volutpat curabitur. Pellentesque suscipit iaculis odio feugiat nisi fermentum semper varius. Eros nulla pulvinar senectus viverra curabitur netus potenti. Porta dictumst est vitae sem nullam penatibus augue ut. Pretium justo aptent efficitur fringilla diam efficitur vitae. Conubia tempus risus eget dis in maecenas quisque amet turpis.</p>
          <p>Scelerisque maximus finibus; neque facilisi lacinia natoque accumsan convallis justo. Aliquam rutrum adipiscing a duis ornare consequat rutrum tempor. Sem fringilla tortor mauris etiam lacus lobortis. Sit accumsan erat, vivamus cubilia ex condimentum ante. Cubilia senectus condimentum libero donec fermentum interdum. Congue rhoncus turpis hac eleifend magnis magna a potenti. Integer tempor ut auctor inceptos posuere morbi. Himenaeos potenti integer ultricies varius litora aptent. Justo cursus hendrerit neque penatibus libero sodales. Turpis fames elit platea, ipsum bibendum morbi lobortis.</p>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
        <h2>Heading 2</h2>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
        <h3>Heading 3</h3>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
          <p>Malesuada sagittis ornare tincidunt mauris fames scelerisque metus magna. Molestie placerat pharetra nunc ultrices volutpat curabitur. Pellentesque suscipit iaculis odio feugiat nisi fermentum semper varius. Eros nulla pulvinar senectus viverra curabitur netus potenti. Porta dictumst est vitae sem nullam penatibus augue ut. Pretium justo aptent efficitur fringilla diam efficitur vitae. Conubia tempus risus eget dis in maecenas quisque amet turpis.</p>
          <p>Scelerisque maximus finibus; neque facilisi lacinia natoque accumsan convallis justo. Aliquam rutrum adipiscing a duis ornare consequat rutrum tempor. Sem fringilla tortor mauris etiam lacus lobortis. Sit accumsan erat, vivamus cubilia ex condimentum ante. Cubilia senectus condimentum libero donec fermentum interdum. Congue rhoncus turpis hac eleifend magnis magna a potenti. Integer tempor ut auctor inceptos posuere morbi. Himenaeos potenti integer ultricies varius litora aptent. Justo cursus hendrerit neque penatibus libero sodales. Turpis fames elit platea, ipsum bibendum morbi lobortis.</p>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
          <p>Malesuada sagittis ornare tincidunt mauris fames scelerisque metus magna. Molestie placerat pharetra nunc ultrices volutpat curabitur. Pellentesque suscipit iaculis odio feugiat nisi fermentum semper varius. Eros nulla pulvinar senectus viverra curabitur netus potenti. Porta dictumst est vitae sem nullam penatibus augue ut. Pretium justo aptent efficitur fringilla diam efficitur vitae. Conubia tempus risus eget dis in maecenas quisque amet turpis.</p>
        <h4>Heading 4</h4>
          <p>Scelerisque maximus finibus; neque facilisi lacinia natoque accumsan convallis justo. Aliquam rutrum adipiscing a duis ornare consequat rutrum tempor. Sem fringilla tortor mauris etiam lacus lobortis. Sit accumsan erat, vivamus cubilia ex condimentum ante. Cubilia senectus condimentum libero donec fermentum interdum. Congue rhoncus turpis hac eleifend magnis magna a potenti. Integer tempor ut auctor inceptos posuere morbi. Himenaeos potenti integer ultricies varius litora aptent. Justo cursus hendrerit neque penatibus libero sodales. Turpis fames elit platea, ipsum bibendum morbi lobortis.</p>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
          <p>Ultricies elementum mus feugiat ligula urna efficitur. Hendrerit condimentum enim vel egestas mus tristique class purus. Curabitur lacus eleifend magna; efficitur eu rhoncus fringilla. Nec dis aliquam magna egestas sociosqu luctus eu turpis. Lobortis suscipit id class ac porta mi scelerisque? Libero urna scelerisque est mus taciti accumsan arcu maecenas facilisi. Maximus habitasse class tellus venenatis blandit.</p>
          <p>Fringilla purus justo pellentesque placerat vivamus mauris. Odio elit platea tristique mus ad facilisis enim. Neque nulla senectus bibendum, cubilia senectus sapien. Hac habitant maximus augue dapibus curae neque aliquet pretium. Donec leo ornare convallis aliquam quis sociosqu massa dapibus. Fusce hac vel magnis; lectus arcu sollicitudin ex taciti? Ex duis malesuada imperdiet laoreet donec quisque nibh. Eros luctus et nascetur malesuada ridiculus facilisis; volutpat conubia.</p>
      </div>
    </Layout>
  );
}
